services:
  ubuntu-texlive-ja:
    image: ghcr.io/tatsumi0000/iosdc2024-pamphlet/texlive-ja:latest
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ~/.gitconfig:/root/.gitconfig
      - ./.latexmkrc:/root/.latexmkrc
    environment:
      SHELL: "/bin/bash"
